### ISSUE TITLE
AT-16001 Upload Course Roaster

### ISSUE THREAD

**Issue by rfpcmaia** [soen341ThinkVision/-ThinkVision-SOEN341_Project_F24-#41]
**ISSUE TRACKING**

This acceptance test is for [US-16](https://github.com/soen341ThinkVision/-ThinkVision-SOEN341_Project_F24-/issues/18), tasks #35 #36 #37 .

See the E2E test running [here](https://youtu.be/ndadgk8b9zY).

**USER ACCEPTANCE FLOW**

1. Instructor logs in and is presented with an option to "Upload Students".
2. Instructor clicks on "Upload Students" and is given the option to "Choose File" to upload a .csv file containing the course roaster.
3. Instructor clicks "Submit" and receives a message if the file was processed correctly.
4. Instructor can return to the homepage and click on "Assign Teams" to see the uploaded students.

**Comment by hugogv12** [comment]
https://youtu.be/8TocjcyctNE
