### ISSUE TITLE
AT-16002 Create Teams

### ISSUE THREAD

**Issue by rfpcmaia** [soen341ThinkVision/-ThinkVision-SOEN341_Project_F24-#42]
**ISSUE TRACKING**

This acceptance test is for [US-16](https://github.com/soen341ThinkVision/-ThinkVision-SOEN341_Project_F24-/issues/18), tasks #38 #39 #40

See the E2E test running [here](https://youtu.be/5r2fr-yxvrQ).

**USER ACCEPTANCE FLOW**

1. In their homepage, the instructor selects an option to "Assign Teams".
2. Instructor can then seen all the students and their current teams (if assigned).
3. Instructor selects the number of students per team, and clicks on "Create Teams".
4. The table of students is updated, showing the teams assigned to each student.
5. From the table, instructor can manually change any student's team.

**Comment by hugogv12** [comment]
https://youtu.be/5r2fr-yxvrQ
