### ISSUE TITLE
Missing Detailed Log

### ISSUE THREAD

**Issue by RukevweOyinloye** [soen341ThinkVision/-ThinkVision-SOEN341_Project_F24-#98]
Hello Team, 
I cannot trace your detailed log documentation for sprint 2. I need immediate response within the next 30 minutes to conclude your scoring for the sprint.

**Comment by hugogv12** [comment]
Hello, It is supposed to be in wiki, and it's called work log. The meeting
minutes are there too

**Comment by RukevweOyinloye** [comment]
i am sorry i will not be able to take this document, you ought to have placed it in your repo sprint folder. if it is there then i can grade it else i cannot

**Comment by rfpcmaia** [comment]
We'll add it to the sprint-2 folder right away!

**Comment by rfpcmaia** [comment]
Also added it to our wiki under "Sprint Planning"
